export const faqs = [
  { q: "¿Cuánto tiempo tarda en llegar mi recarga?", a: "Depende del producto: las recargas directas se acreditan en minutos apenas se valida el pago. Los objetos que se entregan como regalo (la mayoría de los cosméticos) tardan igual de rápido, EXCEPTO si es tu primera compra con nosotros — ahí Epic Games exige 48 horas de amistad antes de poder enviarte el regalo. Cada producto indica cuál de los dos es." },
  { q: "¿Es seguro darles acceso a mi cuenta de Epic Games?", a: "Nunca te vamos a pedir tu contraseña, ni acceso a tu cuenta. Para los regalos, solo necesitamos tu nombre de usuario público de Epic Games (el mismo que usarías para agregar a un amigo dentro del juego) — con eso alcanza para enviarte el artículo." },
  { q: "¿Hace cuánto que venden en Kitson Kit?", a: "Somos una tienda nueva y no te lo vamos a esconder. Preferimos ser transparentes: podés seguir cada paso de tu pedido en tiempo real desde tu cuenta, hablar directo con nosotros por Discord o WhatsApp, y ver quién está del otro lado — no es un bot anónimo respondiendo." },
  { q: "¿Qué pasa si no recibo lo que compré?", a: "Escribinos por Discord o WhatsApp con tu número de pedido y lo resolvemos. Si hubo un error de nuestra parte, te reembolsamos o reenviamos el artículo sin costo." },
  { q: "¿Puedo pagar desde mi país?", a: "Sí. Tenemos métodos locales para México (transferencia y OXXO), Colombia (Nequi), Perú (Yape) y Binance para el resto del mundo. El selector de moneda arriba de todo detecta tu país automáticamente." },
  { q: "¿Qué métodos de pago aceptan?", a: "Aceptamos pagos manuales directos en tu moneda local: Binance, Yape, Nequi, Transferencia Bancaria y Oxxo." },
  { q: "¿Es seguro dar mi ID de jugador?", a: "Totalmente. Solo necesitamos tu ID público o GamerTag para enviarte los artículos. Nunca pediremos tu contraseña." },
  { q: "¿Qué diferencia hay entre 'regalo' y 'recarga directa'?", a: "Los productos marcados como Regalo se entregan dentro del juego, mediante el sistema de regalos de Epic (por eso pueden requerir las 48hs de amistad si es tu primera compra). Los marcados como Recarga directa se acreditan a tu billetera o cuenta sin esa espera." },
  { q: "¿Por qué debería confiar en una tienda nueva?", a: "Porque no te pedimos que confíes a ciegas: podés ver el estado real de tu pedido en todo momento desde /mi-cuenta, hablar con una persona (no un bot) por Discord o WhatsApp antes y después de comprar, y nuestra política de reembolso está escrita en /terminos, no escondida." },
];
